name: /home/chemist/Desktop/sim2real/franka
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=24.0
  - python=3.10.8
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - catkin-pkg==1.0.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - distro==1.9.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docutils==0.21.2
      - etils==1.9.4
      - evdev==1.7.1
      - farama-notifications==0.0.4
      - flax==0.9.0
      - fonttools==4.53.0
      - fsspec==2024.9.0
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gymnasium==0.29.0
      - humanize==4.10.0
      - idna==3.8
      - importlib-resources==6.4.5
      - jax==0.4.32
      - jax-cuda12-pjrt==0.4.32
      - jax-cuda12-plugin==0.4.32
      - jaxlib==0.4.32
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - msgpack==1.1.0
      - mujoco==3.2.2
      - nest-asyncio==1.6.0
      - numpy==1.25.2
      - numpy-quaternion==2023.0.3
      - nvidia-cublas-cu12==12.6.1.4
      - nvidia-cuda-cupti-cu12==12.6.68
      - nvidia-cuda-nvcc-cu12==12.6.68
      - nvidia-cuda-runtime-cu12==12.6.68
      - nvidia-cudnn-cu12==9.4.0.58
      - nvidia-cufft-cu12==11.2.6.59
      - nvidia-cusolver-cu12==11.6.4.69
      - nvidia-cusparse-cu12==12.5.3.3
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.68
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optax==0.2.3
      - orbax-checkpoint==0.6.3
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.3.0
      - platformdirs==4.3.2
      - protobuf==5.28.1
      - psutil==6.0.0
      - pyassimp==5.2.5
      - pygments==2.18.0
      - pynput==1.7.7
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyrealsense2==2.55.1.6486
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytransform3d==3.5.0
      - pytz==2024.2
      - pyyaml==6.0.1
      - requests==2.32.3
      - rich==13.8.1
      - rospkg==1.5.1
      - rospy-message-converter==0.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - tensorboardx==2.6.2.2
      - tensorflow-probability==0.24.0
      - tensorstore==0.1.65
      - termcolor==2.4.0
      - toolz==0.12.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.18.0
      - zipp==3.20.1
